instance = [
    {
        "bbox": [0, 0, 360, 240],
        "fps": 25,
        "frame_end": 2285,
        "frame_start": 2249,
        "instance_id": 0,
        "signer_id": 9,
        "source": "asl5200",
        "split": "test",
        "url": "https://www.youtube.com/watch?v=SiBub8VD5wo",
        "variation_id": 0,
        "video_id": "28074"
      },
      {
        "bbox": [284, 42, 886, 720],
        "fps": 25,
        "frame_end": -1,
        "frame_start": 1,
        "instance_id": 1,
        "signer_id": 118,
        "source": "aslbrick",
        "split": "val",
        "url": "http://aslbricks.org/New/ASL-Videos/hot.mp4",
        "variation_id": 0,
        "video_id": "69368"
      },
      {
        "bbox": [154, 35, 395, 360],
        "fps": 25,
        "frame_end": 4596,
        "frame_start": 4497,
        "instance_id": 2,
        "signer_id": 121,
        "source": "northtexas",
        "split": "val",
        "url": "https://www.youtube.com/watch?v=WGfiiDgrq1I",
        "variation_id": 0,
        "video_id": "70270"
      },
      {
        "bbox": [197, 49, 571, 400],
        "fps": 25,
        "frame_end": -1,
        "frame_start": 1,
        "instance_id": 3,
        "signer_id": 12,
        "source": "aslsearch",
        "split": "train",
        "url": "http://www.aslsearch.com/signs/videos/heat2.mp4",
        "variation_id": 0,
        "video_id": "28125"
      },
      {
        "bbox": [229, 17, 521, 414],
        "fps": 25,
        "frame_end": -1,
        "frame_start": 1,
        "instance_id": 4,
        "signer_id": 36,
        "source": "startasl",
        "split": "train",
        "url": "https://s3-us-west-1.amazonaws.com/files.startasl.com/asldictionary/hot.mp4",
        "variation_id": 0,
        "video_id": "28108"
      },
      {
        "bbox": [351, 11, 818, 480],
        "fps": 25,
        "frame_end": -1,
        "frame_start": 1,
        "instance_id": 5,
        "signer_id": 52,
        "source": "signschool",
        "split": "train",
        "url": "https://signstock.blob.core.windows.net/signschool/videos/db_uploads/SignSchool%20Hot-9X3bjjuKGMM.mp4",
        "variation_id": 0,
        "video_id": "28109"
      },
      {
        "bbox": [657, 78, 1430, 1080],
        "fps": 25,
        "frame_end": -1,
        "frame_start": 1,
        "instance_id": 6,
        "signer_id": 6,
        "source": "signschool",
        "split": "train",
        "url": "https://signstock.blob.core.windows.net/signschool/videos/db_uploads/SignSchool%20Hot-QCvXMjNN4PE.mp4",
        "variation_id": 0,
        "video_id": "28110"
      },
      {
        "bbox": [544, 128, 1596, 1080],
        "fps": 25,
        "frame_end": -1,
        "frame_start": 1,
        "instance_id": 7,
        "signer_id": 39,
        "source": "signschool",
        "split": "train",
        "url": "https://signstock.blob.core.windows.net/signschool/videos/db_uploads/SignSchool%20Hot-wy-09ieHXhM.mp4",
        "variation_id": 0,
        "video_id": "28111"
      },
      {
        "bbox": [61, 4, 500, 480],
        "fps": 25,
        "frame_end": -1,
        "frame_start": 1,
        "instance_id": 8,
        "signer_id": 21,
        "source": "asldeafined",
        "split": "val",
        "url": "https://media.asldeafined.com/vocabulary/1468638601.9688.mp4",
        "variation_id": 0,
        "video_id": "28112"
      },
      {
        "bbox": [114, 9, 538, 480],
        "fps": 25,
        "frame_end": -1,
        "frame_start": 1,
        "instance_id": 9,
        "signer_id": 14,
        "source": "handspeak",
        "split": "train",
        "url": "https://www.handspeak.com/word/h/hot2.mp4",
        "variation_id": 0,
        "video_id": "28113"
      },
      {
        "bbox": [116, 18, 519, 480],
        "fps": 25,
        "frame_end": -1,
        "frame_start": 1,
        "instance_id": 10,
        "signer_id": 20,
        "source": "handspeak",
        "split": "train",
        "url": "https://www.handspeak.com/word/h/hot.mp4",
        "variation_id": 0,
        "video_id": "28114"
      },
      {
        "bbox": [65, 9, 207, 192],
        "fps": 25,
        "frame_end": -1,
        "frame_start": 1,
        "instance_id": 11,
        "signer_id": 11,
        "source": "signingsavvy",
        "split": "train",
        "url": "https://www.signingsavvy.com/signs/mp4/14/14232.mp4",
        "variation_id": 0,
        "video_id": "28115"
      },
      {
        "bbox": [64, 11, 221, 192],
        "fps": 25,
        "frame_end": -1,
        "frame_start": 1,
        "instance_id": 12,
        "signer_id": 11,
        "source": "signingsavvy",
        "split": "train",
        "url": "https://www.signingsavvy.com/signs/mp4/6/6109.mp4",
        "variation_id": 0,
        "video_id": "28116"
      },
      {
        "bbox": [51, 0, 250, 240],
        "fps": 25,
        "frame_end": -1,
        "frame_start": 1,
        "instance_id": 13,
        "signer_id": 0,
        "source": "spreadthesign",
        "split": "train",
        "url": "https://media.spreadthesign.com/video/mp4/13/58462.mp4",
        "variation_id": 0,
        "video_id": "28107"
      },
      {
        "bbox": [316, 30, 937, 720],
        "fps": 25,
        "frame_end": -1,
        "frame_start": 1,
        "instance_id": 15,
        "signer_id": 5,
        "source": "aslu",
        "split": "train",
        "url": "https://www.youtube.com/watch?v=a0robonALIk",
        "variation_id": 0,
        "video_id": "28118"
      },
      {
        "bbox": [142, 37, 410, 339],
        "fps": 25,
        "frame_end": -1,
        "frame_start": 1,
        "instance_id": 16,
        "signer_id": 64,
        "source": "aslu",
        "split": "test",
        "url": "https://www.youtube.com/watch?v=Eya_OdUAevw",
        "variation_id": 0,
        "video_id": "28119"
      },
      {
        "bbox": [329, 36, 980, 720],
        "fps": 25,
        "frame_end": -1,
        "frame_start": 1,
        "instance_id": 17,
        "signer_id": 5,
        "source": "aslu",
        "split": "train",
        "url": "https://www.youtube.com/watch?v=Eya_OdUAevw",
        "variation_id": 0,
        "video_id": "28120"
      },
      {
        "bbox": [328, 34, 937, 720],
        "fps": 25,
        "frame_end": -1,
        "frame_start": 1,
        "instance_id": 18,
        "signer_id": 5,
        "source": "aslu",
        "split": "test",
        "url": "https://www.youtube.com/watch?v=F84dU7A7jI0",
        "variation_id": 0,
        "video_id": "28121"
      },
      {
        "bbox": [293, 31, 955, 720],
        "fps": 25,
        "frame_end": -1,
        "frame_start": 1,
        "instance_id": 19,
        "signer_id": 5,
        "source": "aslu",
        "split": "train",
        "url": "https://www.youtube.com/watch?v=IqCHIu9NrZs",
        "variation_id": 0,
        "video_id": "28122"
      },
      {
        "bbox": [335, 88, 834, 720],
        "fps": 25,
        "frame_end": -1,
        "frame_start": 1,
        "instance_id": 20,
        "signer_id": 65,
        "source": "nabboud",
        "split": "train",
        "url": "https://www.youtube.com/watch?v=Ob3drndU_yM",
        "variation_id": 0,
        "video_id": "28123"
      },
      {
        "bbox": [67, 1, 261, 240],
        "fps": 25,
        "frame_end": -1,
        "frame_start": 1,
        "instance_id": 21,
        "signer_id": 72,
        "source": "aslpro",
        "split": "train",
        "url": "http://www.aslpro.com/main/h/hot.swf",
        "variation_id": 0,
        "video_id": "28124"
      }
    ]


print(f"Total instances: {len(instance)}")